### ISSUE TITLE
Add lines, delete lines and highlight range cannot be combined with range option

### ISSUE THREAD

**Issue by elttuercas** [mistricky/CodeSnap#46]
When using the application to create a screenshot of a range in the given snippet, the `--add-line`, `--delete-line` and `--highlight-range` options don't work as expected.

Using the example file to test out the functionality, `codesnap -f .\cli.sh --range 20:40 --highlight-range 25:30 -o clipboard` produces the following screenshot:
![image](https://github.com/user-attachments/assets/b1ac7581-e243-473a-a4e2-70d08c0ebee0)

As you can see, the lines aren't highlighted. The same issue occurs when trying to mark lines with `--add-line` and `--delete-line`.

**Comment by mistricky** [comment]
Hi @elttuercas, thx for the issue report, the `-a`, `-d`, `--highlight-range` is not works because the **highlight range** is relative to the sliced code snippet.

This means when you specify range `39:40`, and you want to highlight the 39th line, you should pass `--highlight-range 1`, but you're right, this is a little bit counterintuitive, I have fixed this behavior, you can pass `--highlight-range 39` to highlight the 39th line in v0.8.2.

And I also added a new option named `--relative-highlight-range` for users who want to use relative range number.

**Comment by elttuercas** [comment]
Hey, thank you for looking into this. I noticed it was panicking after subtracting the lesser of lines of code and end of range from the start of the range I played around with the code a fair bit to adjust the behaviour and convert the absolute range value into a relative range value by subtracting the start line of the range from the start and end of the range to be highlighted and I ended up making a mess of things compared to the solution you implemented, otherwise I would've submitted a PR myself haha

I probably should mention that I came across this issue by trying to take a snapshot of a ~8500 line file so I'm glad you went with the choice to make the `--highlight-range` argument use the absolute values by default, it's way more convenient with such large files.

I just tested the new version by taking the same screenshot with the same file with which I ran into the problem and it's now behaving as expected so I'll mark the issue as closed, thank you very much!
